---
language: ruby

services:
  - docker

before_install:
  - docker pull robertdebock/docker-revealmd

script:
  - for file in *.md ; do docker run -v $(pwd):/usr/src/app:Z robertdebock/docker-revealmd "${file}" --static output/"${file%.*}" ; done

deploy:
  provider: pages
  local-dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
